### PR TITLE
Create _license.txt

### PR DESCRIPTION
**Pull request by pipedream**
Add GPL licence as per README.

### CODE REVIEW

**Comment by pipedream** [comment]
Rationale:
https://www.gnu.org/licenses/gpl-faq.en.html#WhyMustIInclude
https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary

**Comment by murkle** [comment]
https://github.com/geogebra/geogebra/blob/master/desktop/src/gpl/resources/org/geogebra/desktop/_license.txt

**Comment by pipedream** [comment]
Hi

That doesn't seem to be a license file? More a contributor file?

Not GPL or Geogebra license. As I understand installers are non-commercial but source is GPL, though source without the GPL and with except clauses cannot be GPL... so can the source be licensed with GPL at all? We are interested in redistribution and modified redistribution and packaging, and cannot do so with the current license please.

**Comment by murkle** [comment]
Please email office@geogebra.org and we'll sort you out!

**Comment by jondo** [comment]
So did a modified redistribution and packaging happen, applying Stallman's [software freedoms nr. 2 and 3](https://en.wikipedia.org/wiki/Free_software#Definition_and_the_Four_Freedoms)? I bet not.

Coincidentally, https://www.geogebra.org/license says:

> Please note that GeoGebra as a complete software program would probably not be considered "free" software according to the definition of that term which is used by the Free Software Foundation.

**Pull request closed without merging**
