### PR TITLE
do not create undo points during drag

### PR DESCRIPTION
**Pull request by DailyShana**
and improve undo judge in `applyLineStyle` and `applyColor`

I guess the intention `thicknessChanged` and `alphaChanged` is to avoid too many undo point during drag. Now they are unnecessary.

### CODE REVIEW

**Comment by zbynek** [comment]
This would work in Classic 5 (`desktop` module) but not Classic 6 (`web` module).

**Comment by DailyShana** [comment]
updated for `web` module
and I want to ask how to debug `web` module in IDEA, breakpoint seems not working

**Comment by DailyShana** [comment]
@zbynek Could you look at this?

**Comment by DailyShana** [comment]
conflict caused by https://github.com/geogebra/geogebra/commit/ef1b935eb4258a46ce8ad891454eae8bd691dd96 and https://github.com/geogebra/geogebra/commit/fa94878f2a366f2fc7ae57eba1b6f744dc6ddd29

**Pull request closed without merging**
