### PR TITLE
Fix some cppcheck reports

### PR DESCRIPTION
**Pull request by serval2412**
[giac/src/giac/cpp/derive.cc:339] -> [giac/src/giac/cpp/derive.cc:339]: (style) Same expression on both sides of '||'
[giac/src/giac/cpp/gen.cc:9105] -> [giac/src/giac/cpp/gen.cc:9105]: (style) Same expression on both sides of '||'.
[giac/src/giac/cpp/gen.cc:9131] -> [giac/src/giac/cpp/gen.cc:9131]: (style) Same expression on both sides of '||'.
[giac/src/giac/cpp/maple.cc:1371]: (error) Memory leak: data
[giac/src/giac/cpp/maple.cc:1414]: (error) Memory leak: data
[giac/src/giac/cpp/prog.cc:6489]: (error) Resource leak: f
[giac/src/giac/cpp/ti89.cc:1917] -> [giac/src/giac/cpp/ti89.cc:1917]: (style) Same expression on both sides of '&&'.

### CODE REVIEW

**Comment by serval2412** [comment]
There are other cases I don't know how to fix:
[giac/src/giac/cpp/gausspol.cc:5933] -> [giac/src/giac/cpp/gausspol.cc:5933]: (style) Same expression on both sides of '/'.
[giac/src/giac/cpp/plot.cc:1102] -> [giac/src/giac/cpp/plot.cc:1102]: (style) Same expression on both sides of '/'.
[giac/src/giac/cpp/usual.cc:6760] -> [giac/src/giac/cpp/usual.cc:6760]: (style) Same expression on both sides of '/'.

[giac/src/giac/cpp/alg_ext.cc:995]: (style) Consecutive return, break, continue, goto or throw statements are unnecessary.
[giac/src/giac/cpp/gen.cc:14709]: (style) Consecutive return, break, continue, goto or throw statements are unnecessary.
[giac/src/giac/cpp/plot.cc:625]: (style) Consecutive return, break, continue, goto or throw statements are unnecessary.
[giac/src/giac/cpp/rpn.cc:2680]: (style) Consecutive return, break, continue, goto or throw statements are unnecessary.

[giac/src/giac/cpp/cocoa.cc:14147]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/cocoa.cc:14522]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/ezgcd.cc:585]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/gen.cc:7097]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/gen.cc:9625]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/modpoly.cc:3421]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/pari.cc:229]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/prog.cc:2065]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/quater.cc:65]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/quater.cc:371]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/series.cc:1491]: (style) Statements following return, break, continue, goto or throw will never be executed.
[giac/src/giac/cpp/usual.cc:9046]: (style) Statements following return, break, continue, goto or throw will never be executed.

About these:
[giac/src/giac/cpp/threaded.cc:690]: (error) After push_back(), the iterator 'ktend' may be invalid.
[giac/src/giac/cpp/threaded.cc:836]: (error) After push_back(), the iterator 'ktend' may be invalid.
[giac/src/giac/cpp/threaded.cc:892]: (error) After push_back(), the iterator 'ktend' may be invalid.
[giac/src/giac/cpp/threaded.cc:1169]: (error) After push_back(), the iterator 'ktend' may be invalid.
I think ktend should be recalculated by calling px.end() or p.end() according to the case.

**Comment by murkle** [comment]
Thanks, more fixed committed here: http://dev.geogebra.org/trac/changeset/50628

**Comment by murkle** [comment]
Bernard Parisse says:


[giac/src/giac/cpp/gausspol.cc:5933] -> [giac/src/giac/cpp/gausspol.cc:5933]: (style) Same expression on both sides of '/'.
[giac/src/giac/cpp/plot.cc:1102] -> [giac/src/giac/cpp/plot.cc:1102]: (style) Same expression on both sides of '/'.
[giac/src/giac/cpp/usual.cc:6760] -> [giac/src/giac/cpp/usual.cc:6760]: (style) Same expression on both sides of '/'.

I did not check them all because the source has changed, but 0.0/0.0 is intentional to produce a NaN.

[giac/src/giac/cpp/alg_ext.cc:995]: (style) Consecutive return, break, continue, goto or throw statements are unnecessary.
...
Writing 2 return is a way to comment the second one without the need to add a //
About these:
[giac/src/giac/cpp/threaded.cc:690]: (error) After push_back(), the iterator 'ktend' may be invalid.
[giac/src/giac/cpp/threaded.cc:836]: (error) After push_back(), the iterator 'ktend' may be invalid.
[giac/src/giac/cpp/threaded.cc:892]: (error) After push_back(), the iterator 'ktend' may be invalid.
[giac/src/giac/cpp/threaded.cc:1169]: (error) After push_back(), the iterator 'ktend' may be invalid.
I think ktend should be recalculated by calling px.end() or p.end() according to the case.

No this is not required because push_back happens only when kt==ktend and this will stay so later.
Therefore no changes for these checks...

**Comment by zbynek** [comment]
@serval2412 thanks! As @murkle mentioned above the changes were merged into SVN (which is mirrored to Git), so I'm closing this.

**Pull request closed without merging**
